### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by derwasp** [derwasp/jenkins-jnlp-dind#1]
- [x] Jenkins JNLP slave + Docker In Docker
- [x] Jenkins JNLP slave + Docker In Docker + mono
- [x] Jenkins JNLP slave + Docker In Docker + mono + .NET Core
